### PR TITLE
help message and flag aliases

### PR DESCRIPTION
**Pull request by kyleferguson**
Updates the help message to match options, and adds flag aliases that are documented.

Have you looked at github.com/urfave/cli ? Managing flags and commands is super clean with it. Not real important just wanted to throw it out there.

### CODE REVIEW

**Comment by drasko** [comment]
LGTM, thanks!

@kyleferguson however it is necessary that all contributors sign-off their commits. Please refer to the https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md#pull-requests for details.

By signing-off your commits you are actually also signing [DCO](http://elinux.org/Developer_Certificate_Of_Origin), which permits us to keep a project Apache-2.0 licensed (i.e. to guarantee that there are no lurking patents around).

**Comment by kyleferguson** [comment]
Sorry I hadn't setup key on this machine yet. Should be all good now.

**Comment by nmarcetic** [comment]
LGTM!

**Comment by drasko** [comment]
@kyleferguson instead of github.com/urfave/cli  we used github.com/spf13/cobra in [Mainflux CLI](https://github.com/mainflux/mainflux-cli). However, using a library of this kind would be an overkill here, IMHO. We just need a few command-line options, and I think it would be even better to replace them with ENV vars (looks like an option easier to pass via docker-compose)

**Comment by darkodraskovic** [comment]
Hello Kyle. Thank you very much for your contrib. I've just merged it. We are looking forward for your new contribs.

**Comment by drasko** [comment]
:clap:

**Comment by kyleferguson** [comment]
Awesome thanks!

@drasko yea the reason I mentioned the CLI package is because it makes flags and environment variables simple to manage and you get pretty formatted output/errors out of the box.
For instance right now if you use the CLI incorrect it will print out each flag (even aliases) on separate lines and in alphabetical order
```
--flag Some description
--xxxx Another
-y Another
-z Some description
```

vs urfave/cli which will group it all together nice and pretty, something like
```
--flag, -z Some description. Set VAR1
--xxx, -y Another Set VAR2
```

**Pull request merged**
